CREATE SCHEMA IF NOT EXISTS HWSpring;
CREATE TABLE IF NOT EXISTS HWSpring.Note
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) CHECK (LENGTH(title) BETWEEN 3 AND 200),
    content VARCHAR,
PRIMARY KEY(ID)
);